architecture: replicaset
replicaCount: 2
clusterDomain: "k8s-mongodb"
persistence:
    storageClass: "do-block-storage"
auth:
    enabled: false
metrics:
  enabled: true
   serviceMonitor:
    enabled: true
    namespace: monitoring
