architecture: replicaset
replicaCount: 2
persistence:
    storageClass: "do-block-storage"
auth:
    enabled: false
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    namespace: monitoring
